from datetime import UTC, datetime
import re

import httpx

from .config import get_settings
from .models import Company, ResumeProfile


def profile_text(profile: ResumeProfile) -> str:
    sections = [
        ("Name", profile.name),
        ("Email", profile.email),
        ("Phone", profile.phone),
        ("Location", profile.location),
        ("LinkedIn", profile.linkedin),
        ("GitHub", profile.github),
        ("Website", profile.website),
        ("Education", profile.education_text),
        ("Experience", profile.experience_text),
        ("Projects", profile.projects_text),
        ("Skills", profile.skills_text),
        ("Awards", profile.awards_text),
        ("Other", profile.other_text),
    ]
    return "\n\n".join(
        f"{label}:\n{value}" for label, value in sections if value
    )


def strip_markdown_fence(value: str) -> str:
    value = value.strip()
    value = re.sub(r"^```(?:latex|tex)?\s*", "", value, flags=re.IGNORECASE)
    value = re.sub(r"\s*```$", "", value)
    return value.strip()


def generate_resume(
    company: Company,
    profile: ResumeProfile,
    job_title: str,
    jd_text: str,
    extra_instructions: str,
) -> str:
    settings = get_settings()
    if not settings.enable_ai_features:
        raise RuntimeError("AI resume generation is disabled")
    if not settings.deepseek_api_key:
        raise RuntimeError("DeepSeek API key is not configured")

    system = (
        "You generate truthful, ATS-friendly, Overleaf-compatible resumes. "
        "Return one complete compilable .tex file only, without markdown fences "
        "or explanations. Aim for one page. Use only facts in the supplied base "
        "profile. Never invent experience, dates, degrees, companies, projects, "
        "skills, metrics, or credentials. Emphasize relevant truthful details. "
        "Keep bullets concise. Use standard packages available on Overleaf."
    )
    user = f"""
Company: {company.name}
Job title: {job_title or "unspecified"}

Job description:
{jd_text}

Base resume profile:
{profile_text(profile)}

Extra instructions:
{extra_instructions or "None"}

Return a complete LaTeX resume beginning with \\documentclass and ending with
\\end{{document}}.
""".strip()
    response = httpx.post(
        f"{settings.deepseek_base_url}/chat/completions",
        headers={
            "Authorization": f"Bearer {settings.deepseek_api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.deepseek_model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": 0.2,
        },
        timeout=90,
    )
    response.raise_for_status()
    latex = strip_markdown_fence(
        response.json()["choices"][0]["message"]["content"]
    )
    if "\\documentclass" not in latex or "\\end{document}" not in latex:
        raise RuntimeError("DeepSeek did not return a complete LaTeX document")
    created = datetime.now(UTC).isoformat()
    header = (
        "% Generated by InternRadar\n"
        f"% Company: {company.name}\n"
        f"% Job title: {job_title or 'unspecified'}\n"
        f"% Created: {created}\n"
    )
    return header + latex
