from datetime import UTC, datetime

from sqlalchemy import MetaData, Table, insert, select
from sqlalchemy.orm import Session

from .models import Company


TIERS = ("S+", "S", "A+", "A", "B+", "B", "C", "D")
TIER_SCORES = {
    "S+": 99, "S": 95, "A+": 91, "A": 87,
    "B+": 82, "B": 77, "C": 67, "D": 57,
}
LEGACY_TIER_MAP = {
    "S+": "S+", "S": "S", "A+": "A+", "A": "A",
    "B+": "B+", "B": "B", "C": "C",
}
# Product lines and internal divisions share their parent company's hiring pipeline.
# Independently operated subsidiaries with distinct careers sites remain separate.
MERGED_INTO_PARENT = {
    "Instagram": "Meta",
    "WhatsApp": "Meta",
    "Reality Labs": "Meta",
    "Oculus": "Meta",
    "YouTube": "Google",
    "Google Cloud": "Google",
    "Google Research": "Google",
    "Google Ads": "Google",
    "Microsoft AI": "Microsoft",
    "Azure": "Microsoft",
    "GitHub Copilot": "GitHub",
    "Xbox": "Microsoft",
    "Amazon Web Services": "Amazon",
    "Amazon Robotics": "Amazon",
    "Amazon Lab126": "Amazon",
    "IMDb": "Amazon",
    "Prime Video": "Amazon",
    "Alexa": "Amazon",
    "Apple Machine Learning": "Apple",
    "Apple Vision Pro": "Apple",
    "Beats": "Apple",
    "Shazam": "Apple",
    "CapCut": "ByteDance",
    "Lark": "ByteDance",
    "TikTok": "ByteDance",
    "Tencent Games": "Tencent",
    "TiMi Studio Group": "Tencent",
    "Lightspeed Studios": "Tencent",
    "Huawei Canada": "Huawei",
    "Huawei Research": "Huawei",
    "miHoYo": "HoYoverse",
    "Cognosphere": "HoYoverse",
    "Magna": "Magna International",
    "General Dynamics Mission Systems": "General Dynamics",
    "Raytheon": "RTX",
    "Collins Aerospace": "RTX",
}


CATEGORY_MAP = {
    "AI Lab": "AI & ML",
    "AI Product": "AI & ML",
    "AI Platform": "AI & ML",
    "AI Research": "AI & ML",
    "AI Infrastructure": "AI & ML",
    "AI Hardware": "AI & ML",
    "AI / Biotech": "Health & Biotech",
    "Big Tech": "Big Tech & Consumer",
    "Consumer Tech": "Big Tech & Consumer",
    "Product": "Big Tech & Consumer",
    "Canadian Tech": "Big Tech & Consumer",
    "Microsoft": "Big Tech & Consumer",
    "Amazon": "Big Tech & Consumer",
    "Developer Tools": "Cloud, Data & DevTools",
    "Cloud / Data": "Cloud, Data & DevTools",
    "Cloud / Infrastructure": "Cloud, Data & DevTools",
    "Data Platform": "Cloud, Data & DevTools",
    "Database": "Cloud, Data & DevTools",
    "Analytics": "Cloud, Data & DevTools",
    "Observability": "Cloud, Data & DevTools",
    "Communications": "Enterprise Software",
    "Enterprise": "Enterprise Software",
    "Fintech": "Finance & Trading",
    "Finance": "Finance & Trading",
    "Finance Tech": "Finance & Trading",
    "Canadian Finance": "Finance & Trading",
    "Payments": "Finance & Trading",
    "Quant / Trading": "Finance & Trading",
    "Security": "Security & Networking",
    "Networking": "Security & Networking",
    "Telecom": "Security & Networking",
    "Telecom / Hardware": "Security & Networking",
    "Semiconductors": "Hardware & Semiconductors",
    "Hardware": "Hardware & Semiconductors",
    "Consumer Hardware": "Hardware & Semiconductors",
    "EDA": "Hardware & Semiconductors",
    "Gaming": "Gaming & Media",
    "Automotive": "Robotics & Mobility",
    "Autonomy": "Robotics & Mobility",
    "Robotics": "Robotics & Mobility",
    "Aerospace": "Aerospace & Defense",
    "Aerospace / Defense": "Aerospace & Defense",
    "Defense Tech": "Aerospace & Defense",
    "Data / Defense": "Aerospace & Defense",
    "Consulting / Defense": "Aerospace & Defense",
    "Research / Defense": "Aerospace & Defense",
    "Space Tech": "Aerospace & Defense",
    "Health Tech": "Health & Biotech",
    "Biotech": "Health & Biotech",
    "Biotech Software": "Health & Biotech",
    "Pharma": "Health & Biotech",
    "Industrial": "Industrial & Engineering",
    "Engineering": "Industrial & Engineering",
    "Engineering Software": "Industrial & Engineering",
    "Quantum": "Emerging Tech",
    "Government": "Government & Public Sector",
    "Government Research": "Government & Public Sector",
    "Public Sector": "Government & Public Sector",
    "Pension Fund": "Finance & Trading",
}


def broad_category(category: str) -> str:
    return CATEGORY_MAP.get(category, category)


# SWE/SDE tiers emphasize engineering density, technical scope, compensation,
# career signal, student program quality, and business/role stability.
SWE_TIER_OVERRIDES = {
    "S+": {
        "Anthropic", "Citadel Securities", "D. E. Shaw", "Five Rings",
        "Google DeepMind", "Hudson River Trading", "Jane Street", "OpenAI",
    },
    "S": {
        "Anysphere", "Citadel", "Cognition", "CoreWeave", "Cursor",
        "Databricks", "DRW", "Figma", "Google", "IMC Trading", "Jump Trading",
        "Meta", "Mistral AI", "NVIDIA", "Optiver", "Perplexity", "Stripe",
        "Susquehanna International Group", "Tower Research Capital",
        "Two Sigma", "Waymo", "xAI",
    },
    "A+": {
        "AMD", "Airbnb", "Akuna Capital", "Amazon", "Anduril", "Apple",
        "Applied Intuition", "AQR Capital Management", "Arista Networks", "Arm",
        "Bloomberg", "ByteDance", "Cerebras", "Character.AI", "ClickHouse",
        "Cloudflare", "Cohere", "Coinbase", "Convex", "Datadog", "Decagon",
        "Discord",
        "ElevenLabs", "Figure AI", "Fireworks AI", "GitHub", "Glean", "Groq",
        "Harvey",
        "Headlands Technologies", "Hugging Face", "Linear", "LinkedIn",
        "Magic", "Midjourney", "Microsoft", "Millennium", "Netflix", "Notion",
        "OpenEvidence", "OpenRouter", "Palantir", "Point72", "Poolside", "Ramp",
        "Rippling", "Roblox",
        "Runway", "Safe Superintelligence", "Scale AI", "Shopify", "Sierra AI",
        "Snap", "Snowflake", "SpaceX", "Suno",
        "Thinking Machines Lab", "Together AI", "Uber", "Valve",
        "Virtu Financial", "Waabi", "Wiz",
    },
    "A": {
        "1Password", "Abridge", "Adobe", "Adyen", "Affirm", "Astral",
        "Atlassian", "Aurora", "Benchling", "Block", "Boston Dynamics", "Brex",
        "Broadcom",
        "Baseten", "Braintrust", "Browserbase", "Cadence Design Systems",
        "Canadian Digital Service", "Canva", "Capital One", "Chronosphere",
        "Clerk", "Cockroach Labs", "Communications Security Establishment",
        "Confluent", "CPP Investments", "CrowdStrike", "Crusoe", "Dagster Labs",
        "Docker", "DoorDash", "Dropbox", "Duolingo", "Elastic", "Epic Games",
        "Fastly", "Firecrawl", "Fly.io", "GitLab", "Goldman Sachs",
        "Grafana Labs", "HashiCorp",
        "Helsing", "Honeycomb", "Ideogram", "Instacart", "JetBrains", "Lambda",
        "Langfuse", "Lyft", "Mandiant", "MathWorks", "Mercor", "Miro",
        "Mobileye", "Modal", "MongoDB",
        "MotherDuck", "Neon", "Nintendo", "Nuro", "Okta",
        "Palo Alto Networks", "Pika", "Pinterest", "Plaid",
        "PlanetScale", "Postman", "Pulumi", "Pure Storage", "Recursion",
        "Railway", "Red Hat", "Reddit", "Redis", "Render", "Replicate",
        "Relativity Space", "Replit", "Retool",
        "Riot Games", "Rivos", "Robinhood", "Rubrik", "Samsara", "Sentry",
        "Shield AI", "SiFive", "Skydio", "Slack", "Sourcegraph", "Spotify",
        "Square", "Synthesia",
        "Superhuman", "Supabase", "Synopsys", "Tailscale", "Teleport",
        "Temporal", "Tenstorrent", "Tesla", "Toyota Research Institute",
        "Turso", "Twitch", "Vanta", "Vercel", "Verkada", "Wealthsimple",
        "Weights & Biases", "Weaviate", "Zip", "Zipline", "Zoox", "Zscaler",
        "dbt Labs",
    },
    "B+": {
        "Anaconda", "Analog Devices", "Arize AI", "ASML", "Autodesk",
        "Bank of Canada", "Beacon Software", "CDPQ", "Cisco", "CSIS",
        "Defence Research and Development Canada", "Epirus", "Esri",
        "Forescout", "Fortinet", "Fullscript", "Geotab", "Helicone", "Hopper",
        "Intel", "Intercontinental Exchange", "Intuitive Surgical",
        "JPMorgan Chase", "LangChain", "LlamaIndex", "Marvell", "Mastercard",
        "MDA Space", "MediaTek", "Micron", "Morgan Stanley", "Nango", "Nasdaq",
        "National Research Council Canada", "OMERS",
        "Ontario Teachers' Pension Plan", "Oracle",
        "Qualcomm", "Rivian", "Rocket Lab", "SambaNova Systems", "Samsung",
        "Sanctuary AI", "ServiceNow", "Sony Interactive Entertainment",
        "Solace", "StackAdapt", "Tempus AI", "Tencent", "Terminal",
        "Texas Instruments", "TSMC", "Untether AI", "Varda Space Industries",
        "Vector Institute", "Verily",
        "Visa", "Wolfram", "Xanadu",
    },
    "B": {
        "Borrowell", "Desjardins", "Euna Solutions", "Fellow", "KOHO",
        "Mappedin", "Neo Financial", "Nuvei", "Rewind", "Statistics Canada",
    },
    "C": {
        "Bell", "Huawei", "Rogers", "Shared Services Canada", "TELUS",
    },
    "D": {
        "Amgen", "Johnson & Johnson", "Merck", "Moderna", "Novartis", "Pfizer",
        "Philips", "Roche", "Safran", "Thermo Fisher Scientific",
    },
}

CATEGORY_TIER_POLICY = {
    "AI & ML": {
        "S+": "A+", "S": "A+", "A+": "A", "A": "B+", "B+": "B+", "B": "B",
        "C": "C", "D": "D",
    },
    "Aerospace & Defense": {
        "S+": "A+", "S": "A+", "A+": "A", "A": "B+", "B+": "B", "B": "C",
        "C": "C", "D": "C",
    },
    "Big Tech & Consumer": {
        "S+": "A+", "S": "A+", "A+": "A", "A": "B+", "B+": "B", "B": "C",
        "C": "C", "D": "C",
    },
    "Cloud, Data & DevTools": {
        "S+": "S", "S": "A+", "A+": "A+", "A": "A", "B+": "B+",
        "B": "B", "C": "C", "D": "D",
    },
    "Emerging Tech": {
        "S+": "A+", "S": "A", "A+": "A", "A": "B+", "B+": "B",
        "B": "C", "C": "C", "D": "D",
    },
    "Enterprise Software": {
        "S+": "A+", "S": "A+", "A+": "A", "A": "B+", "B+": "B",
        "B": "C", "C": "C", "D": "D",
    },
    "Finance & Trading": {
        "S+": "S+", "S": "S", "A+": "A+", "A": "A", "B+": "B",
        "B": "C", "C": "C", "D": "C",
    },
    "Gaming & Media": {
        "S+": "A+", "S": "A+", "A+": "A+", "A": "A", "B+": "B",
        "B": "C", "C": "C", "D": "D",
    },
    "Government & Public Sector": {
        "S+": "A", "S": "A", "A+": "B+", "A": "B+", "B+": "B",
        "B": "B", "C": "C", "D": "C",
    },
    "Hardware & Semiconductors": {
        "S+": "S", "S": "S", "A+": "A", "A": "B+", "B+": "B",
        "B": "C", "C": "C", "D": "C",
    },
    "Health & Biotech": {
        "S+": "A+", "S": "A", "A+": "A", "A": "B+", "B+": "B",
        "B": "C", "C": "C", "D": "D",
    },
    "Industrial & Engineering": {
        "S+": "A+", "S": "A", "A+": "A", "A": "B+", "B+": "B",
        "B": "C", "C": "C", "D": "D",
    },
    "Robotics & Mobility": {
        "S+": "S", "S": "S", "A+": "A+", "A": "A", "B+": "B+",
        "B": "B", "C": "C", "D": "C",
    },
    "Security & Networking": {
        "S+": "A+", "S": "A+", "A+": "A+", "A": "A", "B+": "B+",
        "B": "B", "C": "C", "D": "C",
    },
}


def swe_tier_for(name: str, category: str, original_tier: str) -> str:
    for tier, names in SWE_TIER_OVERRIDES.items():
        if name in names:
            return tier
    return CATEGORY_TIER_POLICY[category][original_tier]


# name, domain, tier, category
# Tiers reflect software/quant internship selectivity and career value, not company size.
LEGACY_COMPANIES = [
    # Quant trading and hedge funds
    ("Jane Street", "janestreet.com", "S+", "Quant / Trading"),
    ("Hudson River Trading", "hudsonrivertrading.com", "S+", "Quant / Trading"),
    ("Five Rings", "fiverings.com", "S+", "Quant / Trading"),
    ("D. E. Shaw", "deshaw.com", "S+", "Quant / Trading"),
    ("Citadel Securities", "citadelsecurities.com", "S+", "Quant / Trading"),
    ("Two Sigma", "twosigma.com", "S", "Quant / Trading"),
    ("Optiver", "optiver.com", "S", "Quant / Trading"),
    ("Jump Trading", "jumptrading.com", "S", "Quant / Trading"),
    ("IMC Trading", "imc.com", "S", "Quant / Trading"),
    ("Susquehanna International Group", "sig.com", "S", "Quant / Trading"),
    ("Tower Research Capital", "tower-research.com", "S", "Quant / Trading"),
    ("Citadel", "citadel.com", "S", "Quant / Trading"),
    ("DRW", "drw.com", "A+", "Quant / Trading"),
    ("Millennium", "mlp.com", "A+", "Quant / Trading"),
    ("Point72", "point72.com", "A+", "Quant / Trading"),
    ("AQR Capital Management", "aqr.com", "A+", "Quant / Trading"),

    # Frontier AI and AI-native companies
    ("OpenAI", "openai.com", "S+", "AI Lab"),
    ("Anthropic", "anthropic.com", "S+", "AI Lab"),
    ("Google DeepMind", "deepmind.google", "S+", "AI Lab"),
    ("Safe Superintelligence", "ssi.inc", "S+", "AI Lab"),
    ("Thinking Machines Lab", "thinkingmachines.ai", "S+", "AI Lab"),
    ("xAI", "x.ai", "S", "AI Lab"),
    ("Mistral AI", "mistral.ai", "S", "AI Lab"),
    ("Perplexity", "perplexity.ai", "S", "AI Product"),
    ("Anysphere", "anysphere.inc", "S", "AI Product"),
    ("Cursor", "cursor.com", "S", "AI Product"),
    ("Cohere", "cohere.com", "A+", "AI Lab"),
    ("Scale AI", "scale.com", "A+", "AI Platform"),
    ("Hugging Face", "huggingface.co", "A+", "AI Platform"),
    ("Runway", "runwayml.com", "A+", "AI Product"),
    ("ElevenLabs", "elevenlabs.io", "A+", "AI Product"),
    ("Harvey", "harvey.ai", "A+", "AI Product"),
    ("Character.AI", "character.ai", "A+", "AI Product"),
    ("Replit", "replit.com", "A", "Developer Tools"),

    # Big tech and elite product engineering
    ("NVIDIA", "nvidia.com", "S", "Semiconductors"),
    ("Google", "google.com", "S", "Big Tech"),
    ("Meta", "meta.com", "S", "Big Tech"),
    ("Apple", "apple.com", "A+", "Big Tech"),
    ("Microsoft", "microsoft.com", "A+", "Big Tech"),
    ("Netflix", "netflix.com", "A+", "Big Tech"),
    ("SpaceX", "spacex.com", "A+", "Aerospace"),
    ("Databricks", "databricks.com", "S", "Cloud / Data"),
    ("Stripe", "stripe.com", "S", "Fintech"),
    ("Figma", "figma.com", "S", "Product"),
    ("Palantir", "palantir.com", "A+", "Data / Defense"),
    ("Cloudflare", "cloudflare.com", "A+", "Cloud / Data"),
    ("Snowflake", "snowflake.com", "A+", "Cloud / Data"),
    ("GitHub", "github.com", "A+", "Developer Tools"),
    ("Roblox", "roblox.com", "A+", "Gaming"),
    ("ByteDance", "bytedance.com", "A+", "Consumer Tech"),
    ("TikTok", "tiktok.com", "A+", "Consumer Tech"),
    ("Tesla", "tesla.com", "A", "Automotive"),
    ("Amazon", "amazon.com", "A+", "Big Tech"),

    # Semiconductors, hardware, and devices
    ("AMD", "amd.com", "A+", "Semiconductors"),
    ("Arm", "arm.com", "A+", "Semiconductors"),
    ("ASML", "asml.com", "A+", "Semiconductors"),
    ("TSMC", "tsmc.com", "A+", "Semiconductors"),
    ("Broadcom", "broadcom.com", "A", "Semiconductors"),
    ("Qualcomm", "qualcomm.com", "A", "Semiconductors"),
    ("Samsung", "samsung.com", "A", "Hardware"),
    ("Micron", "micron.com", "A", "Semiconductors"),
    ("Marvell", "marvell.com", "A", "Semiconductors"),
    ("MediaTek", "mediatek.com", "A", "Semiconductors"),
    ("Applied Materials", "appliedmaterials.com", "A", "Semiconductors"),
    ("Lam Research", "lamresearch.com", "A", "Semiconductors"),
    ("KLA", "kla.com", "A", "Semiconductors"),
    ("Texas Instruments", "ti.com", "A", "Semiconductors"),
    ("Analog Devices", "analog.com", "A", "Semiconductors"),
    ("Intel", "intel.com", "A", "Semiconductors"),
    ("Oracle", "oracle.com", "A", "Enterprise"),
    ("IBM", "ibm.com", "B+", "Enterprise"),
    ("Dell Technologies", "dell.com", "B+", "Hardware"),
    ("Western Digital", "westerndigital.com", "B+", "Hardware"),
    ("Seagate", "seagate.com", "B+", "Hardware"),
    ("Garmin", "garmin.com", "B+", "Hardware"),
    ("Motorola Solutions", "motorolasolutions.com", "B+", "Hardware"),
    ("HP", "hp.com", "B", "Hardware"),
    ("Hewlett Packard Enterprise", "hpe.com", "B+", "Enterprise"),
    ("Lenovo", "lenovo.com", "B", "Hardware"),
    ("Sonos", "sonos.com", "B+", "Consumer Hardware"),
    ("Bose", "bose.com", "B+", "Consumer Hardware"),
    ("Logitech", "logitech.com", "B+", "Consumer Hardware"),

    # Cloud, data, developer tools, and observability
    ("MongoDB", "mongodb.com", "A", "Cloud / Data"),
    ("Confluent", "confluent.io", "A", "Cloud / Data"),
    ("Elastic", "elastic.co", "A", "Cloud / Data"),
    ("HashiCorp", "hashicorp.com", "A", "Developer Tools"),
    ("Vercel", "vercel.com", "A", "Developer Tools"),
    ("Datadog", "datadoghq.com", "A+", "Observability"),
    ("Sentry", "sentry.io", "A", "Observability"),
    ("Grafana Labs", "grafana.com", "A", "Observability"),
    ("GitLab", "gitlab.com", "A", "Developer Tools"),
    ("Netlify", "netlify.com", "B+", "Developer Tools"),
    ("DigitalOcean", "digitalocean.com", "B+", "Cloud / Data"),
    ("New Relic", "newrelic.com", "B+", "Observability"),
    ("Splunk", "splunk.com", "B+", "Observability"),

    # Consumer, marketplaces, fintech, and SaaS
    ("Airbnb", "airbnb.com", "A+", "Product"),
    ("Uber", "uber.com", "A+", "Product"),
    ("Coinbase", "coinbase.com", "A+", "Fintech"),
    ("Ramp", "ramp.com", "A+", "Fintech"),
    ("Rippling", "rippling.com", "A+", "Enterprise"),
    ("Notion", "notion.so", "A+", "Product"),
    ("Discord", "discord.com", "A+", "Product"),
    ("DoorDash", "doordash.com", "A", "Product"),
    ("Instacart", "instacart.com", "A", "Product"),
    ("Reddit", "reddit.com", "A", "Product"),
    ("Pinterest", "pinterest.com", "A", "Product"),
    ("Canva", "canva.com", "A", "Product"),
    ("Brex", "brex.com", "A", "Fintech"),
    ("Plaid", "plaid.com", "A", "Fintech"),
    ("Robinhood", "robinhood.com", "A", "Fintech"),
    ("Block", "block.xyz", "A", "Fintech"),
    ("Affirm", "affirm.com", "A", "Fintech"),
    ("Adyen", "adyen.com", "A", "Fintech"),
    ("Shopify", "shopify.com", "A+", "Canadian Tech"),
    ("Wealthsimple", "wealthsimple.com", "A+", "Canadian Tech"),
    ("Chime", "chime.com", "B+", "Fintech"),
    ("Wise", "wise.com", "B+", "Fintech"),
    ("PayPal", "paypal.com", "B+", "Fintech"),
    ("Square", "squareup.com", "A", "Fintech"),
    ("Salesforce", "salesforce.com", "B+", "Enterprise"),
    ("Adobe", "adobe.com", "A", "Enterprise"),
    ("SAP", "sap.com", "B+", "Enterprise"),
    ("ServiceNow", "servicenow.com", "A", "Enterprise"),
    ("Atlassian", "atlassian.com", "A", "Enterprise"),
    ("Workday", "workday.com", "B+", "Enterprise"),
    ("HubSpot", "hubspot.com", "B+", "Enterprise"),
    ("Dropbox", "dropbox.com", "A", "Product"),
    ("Asana", "asana.com", "B+", "Enterprise"),
    ("Monday.com", "monday.com", "B+", "Enterprise"),
    ("Airtable", "airtable.com", "A", "Product"),
    ("Linear", "linear.app", "A+", "Developer Tools"),
    ("Samsara", "samsara.com", "A", "Enterprise"),
    ("Toast", "toasttab.com", "B+", "Enterprise"),
    ("Faire", "faire.com", "B+", "Product"),

    # Finance, payments, and market infrastructure
    ("Morgan Stanley", "morganstanley.com", "A", "Finance"),
    ("Goldman Sachs", "goldmansachs.com", "A+", "Finance"),
    ("JPMorgan Chase", "jpmorganchase.com", "A", "Finance"),
    ("Capital One", "capitalone.com", "A", "Finance"),
    ("Mastercard", "mastercard.com", "A", "Payments"),
    ("Visa", "visa.com", "A", "Payments"),
    ("Bloomberg", "bloomberg.com", "A+", "Finance Tech"),
    ("Nasdaq", "nasdaq.com", "A", "Finance Tech"),
    ("Intercontinental Exchange", "ice.com", "A", "Finance Tech"),
    ("S&P Global", "spglobal.com", "B+", "Finance Tech"),
    ("Thomson Reuters", "thomsonreuters.com", "B+", "Finance Tech"),
    ("Bank of America", "bankofamerica.com", "B+", "Finance"),
    ("American Express", "americanexpress.com", "B+", "Finance"),
    ("RBC", "rbc.com", "B+", "Canadian Finance"),
    ("TD", "td.com", "B+", "Canadian Finance"),
    ("BMO", "bmo.com", "B", "Canadian Finance"),
    ("Scotiabank", "scotiabank.com", "B", "Canadian Finance"),
    ("CIBC", "cibc.com", "B", "Canadian Finance"),
    ("National Bank of Canada", "nbc.ca", "B", "Canadian Finance"),

    # Networking, telecom, and security
    ("Arista Networks", "arista.com", "A+", "Networking"),
    ("Palo Alto Networks", "paloaltonetworks.com", "A", "Security"),
    ("CrowdStrike", "crowdstrike.com", "A", "Security"),
    ("Wiz", "wiz.io", "A+", "Security"),
    ("1Password", "1password.com", "A", "Security"),
    ("Cisco", "cisco.com", "A", "Networking"),
    ("Fortinet", "fortinet.com", "A", "Security"),
    ("Zscaler", "zscaler.com", "A", "Security"),
    ("Okta", "okta.com", "A", "Security"),
    ("SentinelOne", "sentinelone.com", "B+", "Security"),
    ("Snyk", "snyk.io", "B+", "Security"),
    ("Arctic Wolf", "arcticwolf.com", "B+", "Security"),
    ("Proofpoint", "proofpoint.com", "B+", "Security"),
    ("Juniper Networks", "juniper.net", "B+", "Networking"),
    ("Ciena", "ciena.com", "B+", "Networking"),
    ("Ericsson", "ericsson.com", "B+", "Telecom"),
    ("Nokia", "nokia.com", "B", "Telecom"),
    ("TELUS", "telus.com", "B", "Telecom"),
    ("Bell", "bell.ca", "B", "Telecom"),
    ("Rogers", "rogers.com", "B", "Telecom"),

    # Gaming and entertainment
    ("Valve", "valvesoftware.com", "A+", "Gaming"),
    ("Epic Games", "epicgames.com", "A", "Gaming"),
    ("Riot Games", "riotgames.com", "A", "Gaming"),
    ("Nintendo", "nintendo.com", "A", "Gaming"),
    ("Sony Interactive Entertainment", "playstation.com", "A", "Gaming"),
    ("Tencent", "tencent.com", "A", "Gaming"),
    ("Unity", "unity.com", "B+", "Gaming"),
    ("Electronic Arts", "ea.com", "B+", "Gaming"),
    ("HoYoverse", "hoyoverse.com", "B+", "Gaming"),
    ("Take-Two Interactive", "take2games.com", "B+", "Gaming"),
    ("Ubisoft", "ubisoft.com", "B", "Gaming"),

    # Robotics, autonomy, defense, and aerospace
    ("Waymo", "waymo.com", "S", "Autonomy"),
    ("Anduril", "anduril.com", "A+", "Defense Tech"),
    ("Figure AI", "figure.ai", "A+", "Robotics"),
    ("Waabi", "waabi.ai", "A+", "Autonomy"),
    ("Zoox", "zoox.com", "A", "Autonomy"),
    ("Aurora", "aurora.tech", "A", "Autonomy"),
    ("Shield AI", "shield.ai", "A", "Defense Tech"),
    ("Skydio", "skydio.com", "A", "Robotics"),
    ("Zipline", "flyzipline.com", "A", "Robotics"),
    ("Boston Dynamics", "bostondynamics.com", "A", "Robotics"),
    ("Sanctuary AI", "sanctuary.ai", "A", "Robotics"),
    ("Cruise", "getcruise.com", "B+", "Autonomy"),
    ("Intuitive Surgical", "intuitive.com", "A", "Health Tech"),
    ("Rocket Lab", "rocketlabusa.com", "A", "Aerospace"),
    ("Blue Origin", "blueorigin.com", "A", "Aerospace"),
    ("Relativity Space", "relativityspace.com", "A", "Aerospace"),
    ("MDA Space", "mda.space", "A", "Aerospace"),
    ("Planet Labs", "planet.com", "B+", "Space Tech"),
    ("Maxar Technologies", "maxar.com", "B+", "Space Tech"),

    # Aerospace, industrial, automotive, and engineering software
    ("Lockheed Martin", "lockheedmartin.com", "B+", "Aerospace / Defense"),
    ("Northrop Grumman", "northropgrumman.com", "B+", "Aerospace / Defense"),
    ("RTX", "rtx.com", "B+", "Aerospace / Defense"),
    ("Raytheon", "raytheon.com", "B+", "Aerospace / Defense"),
    ("Collins Aerospace", "collinsaerospace.com", "B+", "Aerospace / Defense"),
    ("General Dynamics", "gd.com", "B+", "Aerospace / Defense"),
    ("General Dynamics Mission Systems", "gdmissionsystems.com", "B+", "Aerospace / Defense"),
    ("L3Harris", "l3harris.com", "B+", "Aerospace / Defense"),
    ("BAE Systems", "baesystems.com", "B+", "Aerospace / Defense"),
    ("GE Aerospace", "geaerospace.com", "B+", "Aerospace"),
    ("Boeing", "boeing.com", "B", "Aerospace"),
    ("Airbus", "airbus.com", "B+", "Aerospace"),
    ("Honeywell", "honeywell.com", "B", "Industrial"),
    ("Safran", "safran-group.com", "B", "Aerospace"),
    ("Thales", "thalesgroup.com", "B+", "Aerospace / Defense"),
    ("CAE", "cae.com", "B+", "Aerospace"),
    ("Bombardier", "bombardier.com", "B", "Aerospace"),
    ("Rivian", "rivian.com", "A", "Automotive"),
    ("Lucid Motors", "lucidmotors.com", "B+", "Automotive"),
    ("Toyota Research Institute", "tri.global", "A", "Automotive"),
    ("General Motors", "gm.com", "B+", "Automotive"),
    ("Ford", "ford.com", "B+", "Automotive"),
    ("Magna International", "magna.com", "B", "Automotive"),
    ("Bosch", "bosch.com", "B+", "Industrial"),
    ("Siemens", "siemens.com", "B+", "Industrial"),
    ("Schneider Electric", "se.com", "B+", "Industrial"),
    ("ABB", "abb.com", "B+", "Industrial"),
    ("Emerson", "emerson.com", "B", "Industrial"),
    ("Rockwell Automation", "rockwellautomation.com", "B+", "Industrial"),
    ("Caterpillar", "caterpillar.com", "B", "Industrial"),
    ("John Deere", "deere.com", "B+", "Industrial"),
    ("Autodesk", "autodesk.com", "A", "Engineering Software"),
    ("Esri", "esri.com", "A", "Engineering Software"),
    ("Procore", "procore.com", "B+", "Engineering Software"),
    ("Bentley Systems", "bentley.com", "B+", "Engineering Software"),
    ("Trimble", "trimble.com", "B+", "Engineering Software"),

    # Health tech and Canadian ecosystem
    ("GE HealthCare", "gehealthcare.com", "B+", "Health Tech"),
    ("Siemens Healthineers", "siemens-healthineers.com", "B+", "Health Tech"),
    ("Philips", "philips.com", "B", "Health Tech"),
    ("Medtronic", "medtronic.com", "B+", "Health Tech"),
    ("Boston Scientific", "bostonscientific.com", "B+", "Health Tech"),
    ("StackAdapt", "stackadapt.com", "A", "Canadian Tech"),
    ("Ada", "ada.cx", "B+", "Canadian Tech"),
    ("Xanadu", "xanadu.ai", "A", "Quantum"),
    ("D-Wave", "dwavesys.com", "A", "Quantum"),
    ("Borealis AI", "borealisai.com", "A", "AI Lab"),
    ("Vector Institute", "vectorinstitute.ai", "A", "AI Research"),
    ("BlackBerry", "blackberry.com", "B", "Canadian Tech"),
    ("OpenText", "opentext.com", "B", "Canadian Tech"),
    ("Kinaxis", "kinaxis.com", "B+", "Canadian Tech"),
    ("Lightspeed", "lightspeedhq.com", "B+", "Canadian Tech"),
    ("Coveo", "coveo.com", "B+", "Canadian Tech"),
    ("Clio", "clio.com", "B+", "Canadian Tech"),
    ("League", "league.com", "B+", "Health Tech"),
    ("PointClickCare", "pointclickcare.com", "B+", "Health Tech"),
    ("BenchSci", "benchsci.com", "B+", "Health Tech"),
]

# Additional organizations and product divisions requested for CS/SDE targeting.
ADDITIONAL_COMPANIES = [
    # Major product and research divisions
    ("Instagram", "instagram.com", "A", "Meta"),
    ("WhatsApp", "whatsapp.com", "A", "Meta"),
    ("Reality Labs", "meta.com", "A", "Meta"),
    ("Oculus", "meta.com", "B", "Meta"),
    ("LinkedIn", "linkedin.com", "A", "Microsoft"),
    ("YouTube", "youtube.com", "A", "Google"),
    ("Google Cloud", "cloud.google.com", "S", "Google"),
    ("Google Research", "research.google", "S", "Google"),
    ("Google Ads", "ads.google.com", "A", "Google"),
    ("Microsoft AI", "microsoft.ai", "S", "Microsoft"),
    ("Azure", "azure.microsoft.com", "A", "Microsoft"),
    ("GitHub Copilot", "github.com", "A", "Microsoft"),
    ("Xbox", "xbox.com", "B", "Microsoft"),
    ("Mojang Studios", "mojang.com", "B", "Microsoft"),
    ("Amazon Web Services", "aws.amazon.com", "A", "Amazon"),
    ("Amazon Robotics", "amazonrobotics.com", "A", "Amazon"),
    ("Amazon Lab126", "lab126.com", "A", "Amazon"),
    ("Twitch", "twitch.tv", "A", "Amazon"),
    ("IMDb", "imdb.com", "B", "Amazon"),
    ("Audible", "audible.com", "B", "Amazon"),
    ("Prime Video", "primevideo.com", "B", "Amazon"),
    ("Alexa", "alexa.com", "B", "Amazon"),
    ("Apple Machine Learning", "machinelearning.apple.com", "A", "Apple"),
    ("Apple Vision Pro", "apple.com", "A", "Apple"),
    ("Beats", "beatsbydre.com", "B", "Apple"),
    ("Shazam", "shazam.com", "B", "Apple"),

    # Infrastructure, databases, and developer tools
    ("Docker", "docker.com", "A", "Developer Tools"),
    ("Red Hat", "redhat.com", "A", "Developer Tools"),
    ("Canonical", "canonical.com", "B", "Developer Tools"),
    ("SUSE", "suse.com", "B", "Developer Tools"),
    ("VMware", "vmware.com", "B", "Cloud / Infrastructure"),
    ("Pulumi", "pulumi.com", "A", "Developer Tools"),
    ("Temporal", "temporal.io", "A", "Developer Tools"),
    ("Cockroach Labs", "cockroachlabs.com", "A", "Database"),
    ("PlanetScale", "planetscale.com", "A", "Database"),
    ("Neon", "neon.com", "A", "Database"),
    ("Supabase", "supabase.com", "A", "Database"),
    ("Redis", "redis.io", "A", "Database"),
    ("Neo4j", "neo4j.com", "B", "Database"),
    ("Pinecone", "pinecone.io", "A", "AI Infrastructure"),
    ("Weaviate", "weaviate.io", "A", "AI Infrastructure"),
    ("LangChain", "langchain.com", "A", "AI Infrastructure"),
    ("LlamaIndex", "llamaindex.ai", "A", "AI Infrastructure"),
    ("Postman", "postman.com", "A", "Developer Tools"),
    ("JetBrains", "jetbrains.com", "A", "Developer Tools"),
    ("CircleCI", "circleci.com", "B", "Developer Tools"),
    ("Buildkite", "buildkite.com", "B", "Developer Tools"),
    ("Harness", "harness.io", "B", "Developer Tools"),
    ("JFrog", "jfrog.com", "B", "Developer Tools"),
    ("Sonatype", "sonatype.com", "B", "Developer Tools"),
    ("SonarSource", "sonarsource.com", "B", "Developer Tools"),
    ("Tailscale", "tailscale.com", "A", "Networking"),
    ("Teleport", "goteleport.com", "A", "Security"),
    ("Cloudsmith", "cloudsmith.com", "B", "Developer Tools"),
    ("LaunchDarkly", "launchdarkly.com", "B", "Developer Tools"),

    # SaaS, communications, analytics, and data platforms
    ("PagerDuty", "pagerduty.com", "B", "Observability"),
    ("Honeycomb", "honeycomb.io", "A", "Observability"),
    ("Chronosphere", "chronosphere.io", "A", "Observability"),
    ("Cribl", "cribl.io", "B", "Observability"),
    ("Twilio", "twilio.com", "B", "Communications"),
    ("SendGrid", "sendgrid.com", "B", "Communications"),
    ("Slack", "slack.com", "A", "Enterprise"),
    ("Zoom", "zoom.us", "B", "Enterprise"),
    ("Box", "box.com", "B", "Enterprise"),
    ("DocuSign", "docusign.com", "B", "Enterprise"),
    ("Zendesk", "zendesk.com", "B", "Enterprise"),
    ("Intercom", "intercom.com", "B", "Enterprise"),
    ("Front", "front.com", "B", "Enterprise"),
    ("Gong", "gong.io", "B", "Enterprise"),
    ("Braze", "braze.com", "B", "Enterprise"),
    ("Klaviyo", "klaviyo.com", "B", "Enterprise"),
    ("Amplitude", "amplitude.com", "B", "Analytics"),
    ("Mixpanel", "mixpanel.com", "B", "Analytics"),
    ("Segment", "segment.com", "B", "Data Platform"),
    ("dbt Labs", "getdbt.com", "A", "Data Platform"),
    ("Fivetran", "fivetran.com", "B", "Data Platform"),
    ("Airbyte", "airbyte.com", "B", "Data Platform"),
    ("Astronomer", "astronomer.io", "B", "Data Platform"),
    ("Dagster Labs", "dagster.io", "A", "Data Platform"),
    ("Prefect", "prefect.io", "B", "Data Platform"),
    ("Monte Carlo Data", "montecarlodata.com", "B", "Data Platform"),
    ("Sigma Computing", "sigmacomputing.com", "B", "Data Platform"),
    ("ThoughtSpot", "thoughtspot.com", "B", "Analytics"),
    ("Dremio", "dremio.com", "B", "Data Platform"),
    ("Starburst", "starburst.io", "B", "Data Platform"),
    ("Qlik", "qlik.com", "C", "Analytics"),
    ("Alteryx", "alteryx.com", "C", "Analytics"),
    ("Tableau", "tableau.com", "B", "Analytics"),
    ("Dynatrace", "dynatrace.com", "B", "Observability"),
    ("AppDynamics", "appdynamics.com", "B", "Observability"),

    # Networking, storage, and security
    ("Akamai", "akamai.com", "B", "Networking"),
    ("Fastly", "fastly.com", "A", "Networking"),
    ("F5", "f5.com", "B", "Networking"),
    ("Imperva", "imperva.com", "B", "Security"),
    ("Rapid7", "rapid7.com", "B", "Security"),
    ("Tenable", "tenable.com", "B", "Security"),
    ("Mandiant", "mandiant.com", "A", "Security"),
    ("Check Point", "checkpoint.com", "B", "Security"),
    ("Sophos", "sophos.com", "B", "Security"),
    ("Darktrace", "darktrace.com", "B", "Security"),
    ("Vanta", "vanta.com", "A", "Security"),
    ("Lacework", "lacework.com", "B", "Security"),
    ("Rubrik", "rubrik.com", "A", "Cloud / Infrastructure"),
    ("Cohesity", "cohesity.com", "B", "Cloud / Infrastructure"),
    ("Pure Storage", "purestorage.com", "A", "Cloud / Infrastructure"),
    ("Nutanix", "nutanix.com", "B", "Cloud / Infrastructure"),

    # AI compute and semiconductors
    ("CoreWeave", "coreweave.com", "S", "AI Infrastructure"),
    ("Lambda", "lambda.ai", "A", "AI Infrastructure"),
    ("Crusoe", "crusoe.ai", "A", "AI Infrastructure"),
    ("Cerebras", "cerebras.ai", "A", "AI Hardware"),
    ("Groq", "groq.com", "A", "AI Hardware"),
    ("SambaNova Systems", "sambanova.ai", "A", "AI Hardware"),
    ("Tenstorrent", "tenstorrent.com", "A", "AI Hardware"),
    ("SiFive", "sifive.com", "A", "Semiconductors"),
    ("Rivos", "rivosinc.com", "A", "Semiconductors"),
    ("Graphcore", "graphcore.ai", "B", "AI Hardware"),
    ("Astera Labs", "asteralabs.com", "A", "Semiconductors"),

    # Space, defense, autonomy, and industrial
    ("Astrobotic", "astrobotic.com", "B", "Space Tech"),
    ("Astranis", "astranis.com", "A", "Space Tech"),
    ("Axiom Space", "axiomspace.com", "B", "Space Tech"),
    ("Varda Space Industries", "varda.com", "A", "Space Tech"),
    ("Stoke Space", "stokespace.com", "A", "Space Tech"),
    ("Firefly Aerospace", "fireflyspace.com", "B", "Space Tech"),
    ("Sierra Space", "sierraspace.com", "B", "Space Tech"),
    ("Sierra Nevada Corporation", "sncorp.com", "B", "Aerospace / Defense"),
    ("The Aerospace Corporation", "aerospace.org", "B", "Aerospace / Defense"),
    ("Leidos", "leidos.com", "B", "Aerospace / Defense"),
    ("Booz Allen Hamilton", "boozallen.com", "B", "Consulting / Defense"),
    ("MITRE", "mitre.org", "B", "Research / Defense"),
    ("General Atomics", "ga.com", "B", "Aerospace / Defense"),
    ("Kratos Defense", "kratosdefense.com", "B", "Aerospace / Defense"),
    ("Epirus", "epirusinc.com", "A", "Defense Tech"),
    ("Helsing", "helsing.ai", "A", "Defense Tech"),
    ("Applied Intuition", "applied.co", "A", "Autonomy"),
    ("Nuro", "nuro.ai", "A", "Autonomy"),
    ("Motional", "motional.com", "B", "Autonomy"),
    ("Mobileye", "mobileye.com", "A", "Autonomy"),
    ("Aptiv", "aptiv.com", "B", "Automotive"),
    ("Continental", "continental.com", "C", "Automotive"),
    ("Magna", "magna.com", "C", "Automotive"),
    ("Eaton", "eaton.com", "C", "Industrial"),
    ("Johnson Controls", "johnsoncontrols.com", "C", "Industrial"),
    ("GE Vernova", "gevernova.com", "B", "Industrial"),
    ("Hitachi Energy", "hitachienergy.com", "B", "Industrial"),
    ("Rolls-Royce", "rolls-royce.com", "B", "Aerospace"),
    ("Pratt & Whitney", "prattwhitney.com", "B", "Aerospace"),
    ("Bell Flight", "bellflight.com", "B", "Aerospace"),
    ("Textron", "textron.com", "C", "Aerospace"),
    ("Hexagon", "hexagon.com", "B", "Engineering Software"),
    ("MathWorks", "mathworks.com", "A", "Engineering Software"),
    ("Wolfram", "wolfram.com", "A", "Engineering Software"),
    ("Ansys", "ansys.com", "A", "Engineering Software"),
    ("Cadence Design Systems", "cadence.com", "A", "EDA"),
    ("Synopsys", "synopsys.com", "A", "EDA"),
    ("Keysight Technologies", "keysight.com", "B", "Engineering"),
    ("NI", "ni.com", "B", "Engineering"),

    # Health, biotech, and pharma
    ("Epic Systems", "epic.com", "B", "Health Tech"),
    ("Verily", "verily.com", "A", "Health Tech"),
    ("Flatiron Health", "flatiron.com", "B", "Health Tech"),
    ("Tempus AI", "tempus.com", "A", "Health Tech"),
    ("Benchling", "benchling.com", "A", "Biotech Software"),
    ("Veeva Systems", "veeva.com", "B", "Health Tech"),
    ("10x Genomics", "10xgenomics.com", "B", "Biotech"),
    ("Illumina", "illumina.com", "B", "Biotech"),
    ("Thermo Fisher Scientific", "thermofisher.com", "C", "Biotech"),
    ("Recursion", "recursion.com", "A", "AI / Biotech"),
    ("Ginkgo Bioworks", "ginkgobioworks.com", "B", "Biotech"),
    ("Moderna", "modernatx.com", "C", "Pharma"),
    ("Pfizer", "pfizer.com", "C", "Pharma"),
    ("Roche", "roche.com", "C", "Pharma"),
    ("Johnson & Johnson", "jnj.com", "C", "Pharma"),
    ("Merck", "merck.com", "C", "Pharma"),
    ("Novartis", "novartis.com", "C", "Pharma"),
    ("Amgen", "amgen.com", "C", "Pharma"),

    # China and international product divisions
    ("Huawei", "huawei.com", "B+", "Telecom / Hardware"),
    ("Huawei Canada", "huawei.com", "B", "Canadian Tech"),
    ("Huawei Research", "huawei.com", "A", "AI Research"),
    ("CapCut", "capcut.com", "A", "ByteDance"),
    ("Lark", "larksuite.com", "A", "ByteDance"),
    ("Tencent Games", "tencentgames.com", "B", "Tencent"),
    ("TiMi Studio Group", "timi-studios.com", "B", "Tencent"),
    ("Lightspeed Studios", "lightspeed-studios.com", "B", "Tencent"),
    ("miHoYo", "mihoyo.com", "B", "Gaming"),
    ("Cognosphere", "cognosphere.com", "B", "Gaming"),
    # High-signal SWE employers missing from the original catalog.
    ("Snap", "snap.com", "A+", "Big Tech & Consumer"),
    ("Spotify", "spotify.com", "A", "Big Tech & Consumer"),
    ("Duolingo", "duolingo.com", "A", "Big Tech & Consumer"),
    ("Superhuman", "superhuman.com", "A", "Enterprise Software"),
    ("Glean", "glean.com", "A+", "AI & ML"),
    ("Together AI", "together.ai", "A+", "AI & ML"),
    ("Fireworks AI", "fireworks.ai", "A+", "AI & ML"),
    ("Modal", "modal.com", "A", "Cloud, Data & DevTools"),
    ("Retool", "retool.com", "A", "Cloud, Data & DevTools"),
    ("Miro", "miro.com", "A", "Enterprise Software"),
    ("Verkada", "verkada.com", "A", "Security & Networking"),
    ("Akuna Capital", "akunacapital.com", "A+", "Finance & Trading"),
    ("Virtu Financial", "virtu.com", "A+", "Finance & Trading"),
    ("Headlands Technologies", "headlandstech.com", "A+", "Finance & Trading"),
    ("Quora", "quora.com", "A", "Big Tech & Consumer"),
    # Additional high-signal AI, developer infrastructure, and Canadian SWE employers.
    ("Cognition", "cognition.ai", "S", "AI Product"),
    ("Sierra AI", "sierra.ai", "A+", "AI Product"),
    ("Decagon", "decagon.ai", "A+", "AI Product"),
    ("Abridge", "abridge.com", "A+", "Health Tech"),
    ("Poolside", "poolside.ai", "A+", "AI Lab"),
    ("Magic", "magic.dev", "A+", "AI Lab"),
    ("OpenRouter", "openrouter.ai", "A+", "AI Infrastructure"),
    ("Weights & Biases", "wandb.ai", "A", "AI Platform"),
    ("Anaconda", "anaconda.com", "B+", "Developer Tools"),
    ("Untether AI", "untether.ai", "B+", "AI Hardware"),
    ("Geotab", "geotab.com", "B+", "Canadian Tech"),
    ("Nuvei", "nuvei.com", "B", "Fintech"),
    ("Mappedin", "mappedin.com", "B", "Canadian Tech"),
    ("ClickHouse", "clickhouse.com", "A+", "Database"),
    ("MotherDuck", "motherduck.com", "A", "Database"),
    ("Astral", "astral.sh", "A", "Developer Tools"),
    ("Turso", "turso.tech", "A", "Database"),
    ("Lyft", "lyft.com", "A", "Consumer Tech"),
    # AI products, developer infrastructure, and Canadian employers.
    ("Mercor", "mercor.com", "A", "AI Product"),
    ("OpenEvidence", "openevidence.com", "A+", "Health Tech"),
    ("Midjourney", "midjourney.com", "A+", "AI Product"),
    ("Ideogram", "ideogram.ai", "A", "AI Product"),
    ("Pika", "pika.art", "A", "AI Product"),
    ("Suno", "suno.com", "A+", "AI Product"),
    ("Synthesia", "synthesia.io", "A", "AI Product"),
    ("Replicate", "replicate.com", "A", "AI Infrastructure"),
    ("Baseten", "baseten.co", "A", "AI Infrastructure"),
    ("Sourcegraph", "sourcegraph.com", "A", "Developer Tools"),
    ("Railway", "railway.com", "A", "Cloud / Infrastructure"),
    ("Render", "render.com", "A", "Cloud / Infrastructure"),
    ("Fly.io", "fly.io", "A", "Cloud / Infrastructure"),
    ("Clerk", "clerk.com", "A", "Developer Tools"),
    ("Convex", "convex.dev", "A+", "Database"),
    ("Browserbase", "browserbase.com", "A", "AI Infrastructure"),
    ("Nango", "nango.dev", "B+", "Developer Tools"),
    ("Firecrawl", "firecrawl.dev", "A", "AI Infrastructure"),
    ("Braintrust", "braintrust.dev", "A", "AI Platform"),
    ("Arize AI", "arize.com", "B+", "AI Platform"),
    ("Langfuse", "langfuse.com", "A", "AI Platform"),
    ("Helicone", "helicone.ai", "B+", "AI Platform"),
    ("Beacon Software", "beaconsoftware.com", "B+", "Enterprise"),
    ("Fellow", "fellow.app", "B", "Enterprise"),
    ("Solace", "solace.com", "B+", "Cloud / Infrastructure"),
    ("Rewind", "rewind.com", "B", "Cloud / Data"),
    ("Fullscript", "fullscript.com", "B+", "Health Tech"),
    ("Hopper", "hopper.com", "B+", "Consumer Tech"),
    ("Neo Financial", "neofinancial.com", "B", "Fintech"),
    ("KOHO", "koho.ca", "B", "Fintech"),
    ("Borrowell", "borrowell.com", "B", "Fintech"),
    ("Euna Solutions", "eunasolutions.com", "B", "Enterprise"),
    ("Forescout", "forescout.com", "B+", "Security"),
    ("Terminal", "terminal.io", "B+", "Enterprise"),
    ("Zip", "ziphq.com", "A", "Enterprise"),
    ("Communications Security Establishment", "cse-cst.gc.ca", "A", "Government"),
    ("CSIS", "canada.ca", "B+", "Government"),
    ("Bank of Canada", "bankofcanada.ca", "B+", "Government"),
    ("Statistics Canada", "statcan.gc.ca", "B", "Government"),
    ("Canadian Digital Service", "digital.canada.ca", "A", "Public Sector"),
    ("National Research Council Canada", "nrc.canada.ca", "B+", "Government Research"),
    ("Defence Research and Development Canada", "canada.ca", "B+", "Government Research"),
    ("Shared Services Canada", "canada.ca", "C", "Government"),
    ("CPP Investments", "cppinvestments.com", "A", "Pension Fund"),
    ("OMERS", "omers.com", "B+", "Pension Fund"),
    ("Ontario Teachers' Pension Plan", "otpp.com", "B+", "Pension Fund"),
    ("CDPQ", "cdpq.com", "B+", "Pension Fund"),
    ("Desjardins", "desjardins.com", "B", "Canadian Finance"),
]


def _dedupe_companies():
    companies = []
    seen = set()
    category_details = {}
    for name, domain, tier, category in LEGACY_COMPANIES:
        if name not in seen and name not in MERGED_INTO_PARENT:
            broad = broad_category(category)
            normalized_tier = LEGACY_TIER_MAP[tier]
            companies.append((
                name, domain, swe_tier_for(name, broad, normalized_tier), broad,
            ))
            category_details[name] = category
            seen.add(name)
    for company in ADDITIONAL_COMPANIES:
        if company[0] not in seen and company[0] not in MERGED_INTO_PARENT:
            name, domain, tier, category = company
            broad = broad_category(category)
            companies.append((name, domain, swe_tier_for(name, broad, tier), broad))
            category_details[name] = category
            seen.add(company[0])
    return companies, category_details


COMPANIES, CATEGORY_DETAILS = _dedupe_companies()


CAREER_URLS = {
    # Product divisions use their parent company's official jobs portal.
    "Instagram": "https://www.metacareers.com/jobs",
    "WhatsApp": "https://www.metacareers.com/jobs",
    "Reality Labs": "https://www.metacareers.com/jobs",
    "Oculus": "https://www.metacareers.com/jobs",
    "LinkedIn": "https://careers.linkedin.com/",
    "YouTube": "https://www.google.com/about/careers/applications/jobs/results/?q=YouTube",
    "Google Cloud": "https://www.google.com/about/careers/applications/jobs/results/?q=Google%20Cloud",
    "Google Research": "https://research.google/careers/",
    "Google Ads": "https://www.google.com/about/careers/applications/jobs/results/?q=Ads",
    "Microsoft AI": "https://microsoft.ai/careers/",
    "Azure": "https://jobs.careers.microsoft.com/global/en/search?q=Azure",
    "GitHub": "https://www.github.careers/careers-home",
    "GitHub Copilot": "https://www.github.careers/careers-home",
    "Xbox": "https://careers.microsoft.com/v2/global/en/search-results.html?keywords=Xbox",
    "Mojang Studios": "https://www.minecraft.net/en-us/mojang-careers",
    "Amazon Web Services": "https://www.amazon.jobs/content/en/teams/amazon-web-services",
    "Amazon Robotics": "https://www.amazon.jobs/content/en/teams/amazon-robotics",
    "Amazon Lab126": "https://www.amazon.jobs/content/en/teams/devices-services",
    "Twitch": "https://www.twitch.tv/jobs/",
    "IMDb": "https://www.amazon.jobs/content/en/teams/imdb",
    "Audible": "https://www.audiblecareers.com/",
    "Prime Video": "https://www.amazon.jobs/content/en/teams/prime-video",
    "Alexa": "https://www.amazon.jobs/content/en/teams/devices-services",
    "Apple Machine Learning": "https://jobs.apple.com/en-us/search?team=machine-learning-and-ai-ML-AI",
    "Apple Vision Pro": "https://jobs.apple.com/en-us/search?search=Vision%20Pro",
    "Beats": "https://jobs.apple.com/en-us/search?search=Beats",
    "Shazam": "https://jobs.apple.com/en-us/search?search=Shazam",
    "ByteDance": "https://jobs.bytedance.com/en/",
    "TikTok": "https://lifeattiktok.com/search",
    "CapCut": "https://jobs.bytedance.com/en/",
    "Lark": "https://jobs.bytedance.com/en/",
    "Huawei Canada": "https://career.huawei.com/reccampportal/portal5/index.html",
    "Huawei Research": "https://career.huawei.com/reccampportal/portal5/index.html",
    "Huawei": "https://career.huawei.com/reccampportal/portal5/index.html",
    "Tencent": "https://careers.tencent.com/en-us/home.html",
    "Tencent Games": "https://careers.tencent.com/en-us/home.html",
    "TiMi Studio Group": "https://www.timistudios.com/careers/",
    "Lightspeed Studios": "https://www.lightspeed-studios.com/careers/",
    "HoYoverse": "https://www.hoyoverse.com/en-us/careers",
    "miHoYo": "https://join.mihoyo.com/",
    "Cognosphere": "https://www.hoyoverse.com/en-us/careers",
    "Five Rings": "https://fiverings.com/careers/",
    "Snap": "https://careers.snap.com/",
    "Spotify": "https://www.lifeatspotify.com/jobs",
    "Duolingo": "https://careers.duolingo.com/",
    "Superhuman": "https://superhuman.com/company/careers",
    "Glean": "https://www.glean.com/careers",
    "Together AI": "https://www.together.ai/careers",
    "Fireworks AI": "https://fireworks.ai/careers",
    "Modal": "https://modal.com/careers",
    "Retool": "https://retool.com/careers",
    "Miro": "https://miro.com/careers/",
    "Verkada": "https://www.verkada.com/careers/",
    "Akuna Capital": "https://akunacapital.com/careers/",
    "Virtu Financial": "https://www.virtu.com/careers/",
    "Headlands Technologies": "https://www.headlandstech.com/",
    "Quora": "https://www.quora.com/careers",
    "Cognition": "https://cognition.ai/careers",
    "Sierra AI": "https://sierra.ai/careers",
    "Decagon": "https://decagon.ai/careers",
    "Abridge": "https://www.abridge.com/careers",
    "Poolside": "https://poolside.ai/careers",
    "Magic": "https://magic.dev/careers",
    "OpenRouter": "https://openrouter.ai/careers",
    "Weights & Biases": "https://wandb.ai/careers",
    "Anaconda": "https://www.anaconda.com/about-us/careers",
    "Untether AI": "https://www.untether.ai/careers",
    "Geotab": "https://www.geotab.com/careers/",
    "Nuvei": "https://www.nuvei.com/careers",
    "Mappedin": "https://www.mappedin.com/careers/",
    "ClickHouse": "https://clickhouse.com/company/careers",
    "MotherDuck": "https://motherduck.com/careers/",
    "Astral": "https://astral.sh/careers",
    "Turso": "https://turso.tech/careers",
    "Lyft": "https://www.lyft.com/careers",
    "Mercor": "https://mercor.com/careers",
    "OpenEvidence": "https://www.openevidence.com/careers",
    "Midjourney": "https://www.midjourney.com/jobs",
    "Ideogram": "https://ideogram.ai/careers",
    "Pika": "https://pika.art/careers",
    "Suno": "https://suno.com/careers",
    "Synthesia": "https://www.synthesia.io/careers",
    "Replicate": "https://replicate.com/careers",
    "Baseten": "https://www.baseten.co/careers",
    "Sourcegraph": "https://sourcegraph.com/careers",
    "Railway": "https://railway.com/careers",
    "Render": "https://render.com/careers",
    "Fly.io": "https://fly.io/jobs/",
    "Clerk": "https://clerk.com/careers",
    "Convex": "https://www.convex.dev/jobs",
    "Browserbase": "https://www.browserbase.com/careers",
    "Nango": "https://www.nango.dev/jobs",
    "Firecrawl": "https://www.firecrawl.dev/careers",
    "Braintrust": "https://www.braintrust.dev/careers",
    "Arize AI": "https://arize.com/careers/",
    "Langfuse": "https://langfuse.com/careers",
    "Helicone": "https://www.helicone.ai/careers",
    "Beacon Software": "https://www.beaconsoftware.com/careers",
    "Fellow": "https://fellow.ai/careers",
    "Solace": "https://solace.com/company/careers/",
    "Rewind": "https://rewind.com/careers/",
    "Fullscript": "https://fullscript.com/careers",
    "Hopper": "https://hopper.com/careers",
    "Neo Financial": "https://www.neofinancial.com/careers",
    "KOHO": "https://www.koho.ca/careers/",
    "Borrowell": "https://borrowell.com/careers",
    "Euna Solutions": "https://eunasolutions.com/careers/",
    "Forescout": "https://www.forescout.com/company/careers/",
    "Terminal": "https://www.terminal.io/careers",
    "Zip": "https://ziphq.com/careers",
    "Communications Security Establishment": "https://www.cse-cst.gc.ca/en/careers",
    "CSIS": "https://www.canada.ca/en/security-intelligence-service/corporate/csis-jobs.html",
    "Bank of Canada": "https://www.bankofcanada.ca/careers/",
    "Statistics Canada": "https://www.statcan.gc.ca/en/employment/recruit",
    "Canadian Digital Service": "https://digital.canada.ca/careers/",
    "National Research Council Canada": "https://nrc.canada.ca/en/corporate/careers",
    "Defence Research and Development Canada": "https://www.canada.ca/en/defence-research-development/corporate/job-opportunities.html",
    "Shared Services Canada": "https://www.canada.ca/en/shared-services/corporate/careers.html",
    "CPP Investments": "https://www.cppinvestments.com/careers/",
    "OMERS": "https://www.omers.com/careers",
    "Ontario Teachers' Pension Plan": "https://www.otpp.com/en-ca/careers/",
    "CDPQ": "https://www.cdpq.com/en/careers",
    "Desjardins": "https://www.desjardins.com/ca/careers/",
}


def career_url_for(name: str, domain: str) -> str:
    return CAREER_URLS.get(name, f"https://{domain}/careers")


def seed_companies(db: Session) -> None:
    existing_companies = {
        company.name: company for company in db.scalars(select(Company))
    }
    company_table = Table(
        Company.__tablename__,
        MetaData(),
        autoload_with=db.get_bind(),
    )
    column_names = set(company_table.columns.keys())
    rows = []
    for name, domain, tier, category in COMPANIES:
        if name in existing_companies:
            existing_companies[name].tier = tier
            continue
        now = datetime.now(UTC)
        row = {
            "name": name,
            "display_name": name,
            "parent_company": None,
            "domain": domain,
            "logo_url": f"https://www.google.com/s2/favicons?domain_url=https://{domain}&sz=128",
            "tier": tier,
            "category": category,
            "company_type": CATEGORY_DETAILS[name],
            "career_url": career_url_for(name, domain),
            "main_locations": "",
            "tags": ",".join(dict.fromkeys([
                category.lower().replace(" & ", ",").replace(" ", "-"),
                CATEGORY_DETAILS[name].lower().replace(" / ", ",").replace(" ", "-"),
            ])),
            "global_notes": "",
            "status": "Not Applied",
            "notes": "",
            "link": career_url_for(name, domain),
            "created_at": now,
            "updated_at": now,
            "pay_currency": "USD",
            "pay_period": "unknown",
        }
        rows.append({key: value for key, value in row.items() if key in column_names})
    if rows:
        db.execute(insert(company_table), rows)
    db.commit()
